/// Flutter icons Back
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Back
///      fonts:
///       - asset: fonts/Back.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Back {
  Back._();

  static const _kFontFam = 'Back';
  static const String? _kFontPkg = null;

  static const IconData arrow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
