/// Flutter icons Comm
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Comm
///      fonts:
///       - asset: fonts/Comm.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Comm {
  Comm._();

  static const _kFontFam = 'Comm';
  static const String? _kFontPkg = null;

  static const IconData messege = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
