/// Flutter icons Commicons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Commicons
///      fonts:
///       - asset: fonts/Commicons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Commicons {
  Commicons._();

  static const _kFontFam = 'Commicons';
  static const String? _kFontPkg = null;

  static const IconData invest = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dollar = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shake = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
