/// Flutter icons Partner
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Partner
///      fonts:
///       - asset: fonts/Partner.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Partner {
  Partner._();

  static const _kFontFam = 'Partner';
  static const String? _kFontPkg = null;

  static const IconData invest = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stars = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData accept = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
